# Social Perception Towards GenAI

---

#Context & Motivation

From Kaggle: https://www.kaggle.com/datasets/arinjaypathak/generative-ai-tweets

About Dataset
Generative AI, ever since ChatGPT has become popular, is a term we are getting to hear very often. This dataset contains all tweets having "#GenerativeAI" from 20th April, 2022 to 20th April, 2023. This dataset can be used for the following tasks-

Finding trends- Difference between the frequency of the term Generative AI, before and after ChatGPT release.
Opinion Mining- Finding opinion the tweets have about Generative AI using text clustering.
Generating further tweets(by fine tuning GPT2, for eg)
Profile wise analysis of the users mostly tweeting about Generative AI.

# Goal of the project

random random random randomrandom randomrandom randomrandom randomrandom randomrandom randomrandom randomrandom randomrandom randomrandom randomrandom randomrandom randomrandom randomrandom randomrandom randomrandom random

# Imports & Installs

In [ ]:
"""
import modules
"""
import numpy as np
import pandas as pd
import altair as alt
from datetime import datetime,timezone
from nltk.tokenize import sent_tokenize, word_tokenize
import nltk
from nltk.corpus import stopwords
import re
from nltk.sentiment import SentimentIntensityAnalyzer



alt.__version__

'4.2.2'

In [ ]:
"""
Pip installs only do on fresh enviroments
"""
# pip install nltk
# pip install altair
# pip install pandaas
# pip install numpy

'\nPip installs only do on fresh enviroments\n'

In [ ]:
# Vader download for sentiment
nltk.download('vader_lexicon')
# Create an instance of the sentiment analyzer
analyzer = SentimentIntensityAnalyzer()

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [ ]:
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

# Data Preprocessing/EDA

In [ ]:
# Upload to Colab notebook on the left
df = pd.read_csv('/content/GenerativeAI_tweets.csv')

In [ ]:
df.head(20)

,Unnamed: 0,Datetime,Tweet Id,Text,Username
0,0,2023-04-19 21:27:19+00:00,1648800467206672384,From Studio Gangster to Synthetic Gangster 🎤.....,resembleai
1,1,2023-04-19 21:27:09+00:00,1648800425540476929,Took me some time to find this. I build this #...,devaanparbhoo
2,2,2023-04-19 21:26:57+00:00,1648800376479715328,Mind blowing next wave #generativeai platform...,timreha
3,3,2023-04-19 21:26:49+00:00,1648800341193027584,Open Source Generative AI Image Specialist Sta...,VirtReview
4,4,2023-04-19 21:25:00+00:00,1648799883934203905,Are you an #HR leader considering which future...,FrozeElle
5,5,2023-04-19 21:23:39+00:00,1648799544375754754,#GenerativeAI is a new technology that can cre...,rmlopez13
6,6,2023-04-19 21:21:48+00:00,1648799078342426625,Salesforce announces plans to integrate Einste...,annebonnerdata
7,7,2023-04-19 21:20:32+00:00,1648798761366241281,Discover the limitless possibilities of #Gener...,MarcoVespa
8,8,2023-04-19 21:18:28+00:00,1648798240656199681,Local art fam: Come join us at Adobe SF to lea...,hepkitten
9,9,2023-04-19 21:17:13+00:00,1648797925600817153,Salesforce announces plans to integrate Einste...,VentureBeat
10,10,2023-04-19 21:17:02+00:00,1648797880583442433,Check out my latest article: Four Ways #Genera...,MaribelLopez
11,11,2023-04-19 21:17:00+00:00,1648797870932254720,"This week on Big Martech, the second installat...",podlablk
12,12,2023-04-19 21:10:09+00:00,1648796148457406465,"@MoldyWarp Here are the images you requested, ...",diffusionbot
13,13,2023-04-19 21:10:02+00:00,1648796120183652352,Three Ways Media Leaders Can Leverage Generati...,genztutz
14,14,2023-04-19 21:08:01+00:00,1648795611175460865,#CreatorEconomy - 💭 Is creativity at risk? As ...,AlexisGoncalves
15,15,2023-04-19 21:07:48+00:00,1648795557907841024,Acquire a premium AI startup domain!\nStill av...,AIStartupNames
16,16,2023-04-19 21:07:09+00:00,1648795394141310977,Midjourney and Adobe Firefly Prompts\n\n#adobe...,chatgptcrafters
17,17,2023-04-19 21:03:00+00:00,1648794347188498432,Creating Snowflake UDFs with ChatGPT: A Guide ...,ddskier
18,18,2023-04-19 21:02:20+00:00,1648794179814711299,One more. Starting to get to grips with this w...,TomLikesRobots
19,19,2023-04-19 21:02:05+00:00,1648794119265763331,A person's surprised face as they spot a celeb...,unrealpixels

In [ ]:
df.count()

Unnamed: 0    56221
Datetime      56221
Tweet Id      56221
Text          56221
Username      56221
dtype: int64

In [ ]:
# Unique twitter account names with top 30 tweet counts could be worht exploring their tweets
user_count_top_30 = df['Username'].value_counts()[0:30]
user_count_top_30

diffusionbot       3032
androiddream_ai    2291
SpirosMargaris      738
UniMatrixZ0         700
cuwyl               432
PhilippeJB_PJB      398
aneesmerchant       359
anthonyhadfiel7     345
joseantonio11       337
Maketplans          310
BenedicteJester     290
stratorob           252
xodapi              236
Mlearning_ai        226
wellthatwasdeep     198
MktgAi              195
AI_is_present       192
real_alethea        166
_nxmstagram         161
laphalenelibre      160
a23m384             160
Gross_sculptor      159
HKs_EyesOnYou       152
andresvilarino      152
NanaosMf            151
enilev              148
alvinfoo            143
retr0metr0          139
c4chaos             139
enricomolinari      139
Name: Username, dtype: int64

In [ ]:
# looking for
user_diffussionbot = df[df['Username'] == 'diffusionbot']

user_diffussionbot.head(20)

,Unnamed: 0,Datetime,Tweet Id,Text,Username
12,12,2023-04-19 21:10:09+00:00,1648796148457406465,"@MoldyWarp Here are the images you requested, ...",diffusionbot
211,211,2023-04-19 16:27:10+00:00,1648724933810221061,"@MoldyWarp Here are the images you requested, ...",diffusionbot
219,219,2023-04-19 16:23:02+00:00,1648723893991997440,"@MoldyWarp Here are the images you requested, ...",diffusionbot
893,893,2023-04-18 23:22:11+00:00,1648466989399306241,"@MoldyWarp Here are the images you requested, ...",diffusionbot
1035,1035,2023-04-18 19:04:46+00:00,1648402207061016576,"@MoldyWarp Here are the images you requested, ...",diffusionbot
1331,1331,2023-04-18 13:31:15+00:00,1648318272717160452,"@MoldyWarp Here are the images you requested, ...",diffusionbot
1497,1497,2023-04-18 10:28:25+00:00,1648272262003412993,"@MoldyWarp Here are the images you requested, ...",diffusionbot
1832,1832,2023-04-17 21:49:46+00:00,1648081341169254402,"@MoldyWarp Here are the images you requested, ...",diffusionbot
1833,1833,2023-04-17 21:48:01+00:00,1648080902663143425,"@MoldyWarp Here are the images you requested, ...",diffusionbot
1836,1836,2023-04-17 21:39:54+00:00,1648078857516220422,"@MoldyWarp Here are the images you requested, ...",diffusionbot
1847,1847,2023-04-17 21:14:59+00:00,1648072590748008449,"@MoldyWarp Here are the images you requested, ...",diffusionbot
1870,1870,2023-04-17 20:43:04+00:00,1648064554830647328,"@MoldyWarp Here are the images you requested, ...",diffusionbot
1872,1872,2023-04-17 20:32:26+00:00,1648061881628741634,"@MoldyWarp Here are the images you requested, ...",diffusionbot
1873,1873,2023-04-17 20:30:51+00:00,1648061483446566912,"@MoldyWarp Here are the images you requested, ...",diffusionbot
2126,2126,2023-04-17 14:51:49+00:00,1647976163275317252,"@MoldyWarp Here are the images you requested, ...",diffusionbot
2130,2130,2023-04-17 14:49:27+00:00,1647975564475609089,"@MoldyWarp Here are the images you requested, ...",diffusionbot
2131,2131,2023-04-17 14:48:19+00:00,1647975279325847552,"@MoldyWarp Here are the images you requested, ...",diffusionbot
2214,2214,2023-04-17 13:13:06+00:00,1647951320559566856,"@MoldyWarp Here are the images you requested, ...",diffusionbot
2649,2649,2023-04-16 19:09:49+00:00,1647678703504179200,"@MoldyWarp Here are the images you requested, ...",diffusionbot
2707,2707,2023-04-16 17:30:31+00:00,1647653711005597696,"@MoldyWarp Here are the images you requested, ...",diffusionbot

In [ ]:
user_diffussionbot['Text'][2707]

'@MoldyWarp Here are the images you requested, courtesy of #StableDiffusion.\nPlease retweet &amp; ♥️ if you enjoyed these images. #GenerativeAI, #GenerativeArt, #AIArt, #PromptSharing https://t.co/QI6brH5nY0'

In [ ]:
"""
Not accurate there's some differences you can see above
of very similar tweets but not exactly unique
"""
tweet_count_top_30 = df['Text'].value_counts()[0:10]
tweet_count_top_30

#GenerativeAI                                                                                                                                                                                                                                                                              24
Say goodbye to tedious messaging and hello to effortless communication with our latest generative AI features!\n\nDiscover the power of AI with Pragma's Chrome Extension\n#ai #generativeai #chromeextension #chatgpt #gpt3                                                               17
@realBGem @generaitiv #generativeAi @Zk_brain                                                                                                                                                                                                                                               8
Google Cloud CISO Phil Venables: Zero trust ‘essential’ to protect the cloud https://t.co/d8OYde4TMS #business #EdgeAI #GenerativeAI #GoogleCloud                                                                                                                                           6
Beyond The Hype:   What You Really Need To Know About #AI In 2023   https://t.co/3rZktuWVM4 #AI #ArtificialIntelligence #MachineLearning #DeepLearning #GenerativeAI                                                                                                                        6
https://t.co/TSE7q1mLb5 tackles conversational AI pain points with new design tool https://t.co/gkDvJTtUzT #AI #AI,MLAndDeepLearning #ConversationalAI #GenerativeAI                                                                                                                        6
#ChatGPT is dominating headlines and its explosive global popularity has shown the transformative potential of #GenerativeAI and Large Language Models. No company can afford to ignore this era-defining shift. \n \nDiscover more in @Accenture’s new report. https://t.co/sT5AB4Olc0     6
WEBINAR: Will ChatGPT forever change #education? Join @DataInnovation's @g1lliandiebold alongside panelists @torreytrust &amp; @jryoung as they discuss the #promises &amp; #pitfalls of #generativeAI in the #classroom. Register for the #webinar now:  https://t.co/wod7PYprcU           5
Are you an #HR leader considering which future trends to prioritize? Watch this 3-part series w/ @holgermu &amp; @diginomica co-founder @jonerp analyzing @workday's 2023 #AI &amp; #ML Summit, and broader #GenerativeAI and HR trends shaping the industry. https://t.co/huOMKqtJcx       5
An Overview of #GenerativeAI [Infographic] https://t.co/sbnXFATtgn #AI                                                                                                                                                                                                                      5
Name: Text, dtype: int64

In [ ]:
username_values = user_count_top_30.index.tolist()

usertop30_with_tweet = df[df['Username'].isin(username_values)]

usertop30_with_tweet

,Unnamed: 0,Datetime,Tweet Id,Text,Username
12,12,2023-04-19 21:10:09+00:00,1648796148457406465,"@MoldyWarp Here are the images you requested, ...",diffusionbot
36,36,2023-04-19 20:30:02+00:00,1648786050842599428,Calls for stricter #UK oversight of #workplace...,aneesmerchant
74,74,2023-04-19 19:30:03+00:00,1648770955265572867,A nine-figure #raise in #fintech? Oh my \n\nht...,aneesmerchant
81,81,2023-04-19 19:13:36+00:00,1648766815710085120,Midjourney Prompt: Ross @GerberKawasaki playin...,c4chaos
113,113,2023-04-19 18:27:32+00:00,1648755223458988032,⭐My highlight of the day!\n\n💯With the right p...,_nxmstagram
...,...,...,...,...,...
55792,55792,2022-09-14 04:44:01+00:00,1569909813848465410,Successful #generativeAI examples \n\nworth no...,SpirosMargaris
55804,55804,2022-09-12 04:14:52+00:00,1569177700178317312,4 Hot Takes About \n\nThe Wild New World Of #G...,SpirosMargaris
55828,55828,2022-09-04 05:48:02+00:00,1566302043240894464,We are the #artist: \n\n#GenerativeAI and the ...,SpirosMargaris
55835,55835,2022-09-02 07:31:00+00:00,1565603179827445760,Top 10 #IntelligentAutomationTrends to Lookout...,andresvilarino
56207,56207,2022-04-26 06:16:03+00:00,1518836283417804800,"Understanding #GenerativeAI, \n\nIts Impacts a...",SpirosMargaris

# **Cleaned Data**

Data above is really tough to work with, going to clean text data to remove symbols, and put everything in lowercase to eventually tokenize words

In [ ]:
# Function to clean data with numbers

def  clean_text_with_numbers(df_original: df, text_field: str, new_text_field_name: str):
    df = df_original.copy()
    df[new_text_field_name] = df[text_field].str.lower()
    df[new_text_field_name] = df[new_text_field_name].apply(lambda elem: re.sub(r"(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)|^rt|http.+?", "", elem))
    return df

# Function to clean data without numbers
def  clean_text_without_numbers(df_original: df, text_field: str, new_text_field_name: str):
    df = df_original.copy()
    df[new_text_field_name] = df[text_field].str.lower()
    df[new_text_field_name] = df[new_text_field_name].apply(lambda elem: re.sub(r"(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)|^rt|http.+?", "", elem))
    # remove numbers
    df[new_text_field_name] = df[new_text_field_name].apply(lambda elem: re.sub(r"\d+", "", elem))
    return df

In [ ]:
tweet_clean_no_numbers = clean_text_without_numbers(df,'Text','clean_tweet')
tweet_clean_no_numbers

,Unnamed: 0,Datetime,Tweet Id,Text,Username,clean_tweet
0,0,2023-04-19 21:27:19+00:00,1648800467206672384,From Studio Gangster to Synthetic Gangster 🎤.....,resembleai,from studio gangster to synthetic gangster we...
1,1,2023-04-19 21:27:09+00:00,1648800425540476929,Took me some time to find this. I build this #...,devaanparbhoo,took me some time to find this i build this no...
2,2,2023-04-19 21:26:57+00:00,1648800376479715328,Mind blowing next wave #generativeai platform...,timreha,mind blowing next wave generativeai platform ...
3,3,2023-04-19 21:26:49+00:00,1648800341193027584,Open Source Generative AI Image Specialist Sta...,VirtReview,open source generative ai image specialist sta...
4,4,2023-04-19 21:25:00+00:00,1648799883934203905,Are you an #HR leader considering which future...,FrozeElle,are you an hr leader considering which future ...
...,...,...,...,...,...,...
56216,56216,2022-04-24 16:40:01+00:00,1518268535276904448,"Understanding Generative AI, Its Impacts and L...",analyticsinme,understanding generative ai its impacts and li...
56217,56217,2022-04-23 07:23:24+00:00,1517766068592381952,Y ya puedes empezar a crear #arte con @thegeni...,iia_es,y ya puedes empezar a crear arte con y obtene...
56218,56218,2022-04-22 08:20:21+00:00,1517418013812830208,"NVIDIA researchers have developed GANverse3D, ...",VideoGenAI,nvidia researchers have developed ganversed an...
56219,56219,2022-04-21 13:15:21+00:00,1517129866403008512,Tech Trend 2022: เทรนด์เทคโนโลยีสำหรับปี 2022 ...,sitthinuntp,tech trend gartner technology technolog...
56220,56220,2022-04-21 08:59:57+00:00,1517065592817209344,"Hey Google, Siri, Alexa, Bixbi: draw me a pict...",VideoGenAI,hey google siri alexa bixbi draw me a picture ...

In [ ]:
tweet_clean_with_numbers = clean_text_with_numbers(df,'Text','clean_tweet_numbers')
tweet_clean_with_numbers

,Unnamed: 0,Datetime,Tweet Id,Text,Username,clean_tweet_numbers
0,0,2023-04-19 21:27:19+00:00,1648800467206672384,From Studio Gangster to Synthetic Gangster 🎤.....,resembleai,from studio gangster to synthetic gangster we...
1,1,2023-04-19 21:27:09+00:00,1648800425540476929,Took me some time to find this. I build this #...,devaanparbhoo,took me some time to find this i build this no...
2,2,2023-04-19 21:26:57+00:00,1648800376479715328,Mind blowing next wave #generativeai platform...,timreha,mind blowing next wave generativeai platform ...
3,3,2023-04-19 21:26:49+00:00,1648800341193027584,Open Source Generative AI Image Specialist Sta...,VirtReview,open source generative ai image specialist sta...
4,4,2023-04-19 21:25:00+00:00,1648799883934203905,Are you an #HR leader considering which future...,FrozeElle,are you an hr leader considering which future ...
...,...,...,...,...,...,...
56216,56216,2022-04-24 16:40:01+00:00,1518268535276904448,"Understanding Generative AI, Its Impacts and L...",analyticsinme,understanding generative ai its impacts and li...
56217,56217,2022-04-23 07:23:24+00:00,1517766068592381952,Y ya puedes empezar a crear #arte con @thegeni...,iia_es,y ya puedes empezar a crear arte con y obtene...
56218,56218,2022-04-22 08:20:21+00:00,1517418013812830208,"NVIDIA researchers have developed GANverse3D, ...",VideoGenAI,nvidia researchers have developed ganverse3d a...
56219,56219,2022-04-21 13:15:21+00:00,1517129866403008512,Tech Trend 2022: เทรนด์เทคโนโลยีสำหรับปี 2022 ...,sitthinuntp,tech trend 2022 2022 gartner technology t...
56220,56220,2022-04-21 08:59:57+00:00,1517065592817209344,"Hey Google, Siri, Alexa, Bixbi: draw me a pict...",VideoGenAI,hey google siri alexa bixbi draw me a picture ...

In [ ]:
tweet_count_top_30_clean = tweet_clean_no_numbers['clean_tweet'].value_counts()[0:10]
tweet_count_top_30_clean

 here are the images you requested courtesy of stablediffusionplease retweet amp  if you enjoyed these images generativeai generativeart aiart promptsharing                                                                                   1846
here are the images you requested courtesy of stablediffusionplease retweet amp  if you enjoyed these images generativeai generativeart aiart promptsharing                                                                                     456
 here are the images you requested courtesy of stablediffusionplease retweet amp  if you enjoyed these images generativeai                                                                                                                      260
here are the images you requested courtesy of stablediffusionplease retweet amp  if you enjoyed these images generativeai                                                                                                                       253
i just signed up to try autodesigner a new generative ai by  for uiux design looks incredible  generativeai autodesigner uidesign uxdesign                                                                                                      215
fall winter collection    architecture ai generativeai futuristicdesign design architectureinspiration architecturaldesign homedesign innovation                                                                                                210
art illustration digitalillustration digitalarts aiartwork womboart wombo digitalart aiart comicart generativeart generativeai                                                                                                                  190
chatgpt is dominating headlines and its explosive global popularity has shown the transformative potential of generativeai and large language models no company can afford to ignore this eradefining shift  discover more in s new report      103
 launches einstein gpt the worlds first generativeai for crm which delivers aicreated content across every sales marketing commerce amp it interaction at hyperscalediscover how einsteingpt is transforming customer experiences                88
midjourney generativeart generativeai art digitalart aiartworks digitalartist                                                                                                                                                                    78
Name: clean_tweet, dtype: int64

In [ ]:
username_values = user_count_top_30.index.tolist()

usertop30_with_tweet_cleaned = tweet_clean_no_numbers[tweet_clean_no_numbers['Username'].isin(username_values)]

usertop30_with_tweet_cleaned

top30_dropped_columns = usertop30_with_tweet_cleaned.drop(['Tweet Id', 'Unnamed: 0','Text','Datetime'],axis = 1)
reset_df = top30_dropped_columns.reset_index(drop = True)
reset_df

             Username                                        clean_tweet
0        diffusionbot   here are the images you requested courtesy of...
1       aneesmerchant  calls for stricter uk oversight of workplace a...
2       aneesmerchant  a ninefigure raise in fintech oh my  artificia...
3             c4chaos  midjourney prompt ross  playing guitar dressed...
4         _nxmstagram  my highlight of the daywith the right prompts ...
...               ...                                                ...
12495  SpirosMargaris  successful generativeai examples worth noting ...
12496  SpirosMargaris   hot takes about the wild new world of generat...
12497  SpirosMargaris  we are the artist generativeai and the future ...
12498  andresvilarino  top  intelligentautomationtrends to lookout fo...
12499  SpirosMargaris  understanding generativeai its impacts and lim...

[12500 rows x 2 columns]

In [ ]:
reset_df.value_counts()[0:10]

Username         clean_tweet
diffusionbot      here are the images you requested courtesy of stablediffusionplease retweet amp  if you enjoyed these images generativeai generativeart aiart promptsharing       1846
                 here are the images you requested courtesy of stablediffusionplease retweet amp  if you enjoyed these images generativeai generativeart aiart promptsharing         456
                  here are the images you requested courtesy of stablediffusionplease retweet amp  if you enjoyed these images generativeai                                          260
                 here are the images you requested courtesy of stablediffusionplease retweet amp  if you enjoyed these images generativeai                                           253
Maketplans       fall winter collection    architecture ai generativeai futuristicdesign design architectureinspiration architecturaldesign homedesign innovation                    210
BenedicteJester  art illustration digitalillustration digitalarts aiartwork womboart wombo digitalart aiart comicart generativeart generativeai                                      190
diffusionbot       here are the images you requested courtesy of stablediffusionplease retweet amp  if you enjoyed these images generativeai generativeart aiart promptsharing        55
                    here are the images you requested courtesy of stablediffusionplease retweet amp  if you enjoyed these images generativeai generativeart aiart promptsharing       45
Maketplans       spring summer collection    architecture generativeai midjourneyv                                                                                                    38
                 spring summer collection    architecture ai generativeai futuristicdesign design architectureinspiration architecturaldesign homedesign innovation                   36
dtype: int64

In [ ]:
test_text = reset_df['clean_tweet'][0]
test_text

' here are the images you requested courtesy of stablediffusionplease retweet amp  if you enjoyed these images generativeai generativeart aiart promptsharing '

In [ ]:
sentiment_scores = analyzer.polarity_scores(test_text)
print(sentiment_scores)

{'neg': 0.0, 'neu': 0.756, 'pos': 0.244, 'compound': 0.7003}

From above I think we have too many words that don't really mean much so neutral scores seem a little high, will need to use stop words and clean data even more

In [ ]:
# Function to filter stop words
def filter_stop_words(text):
    words = nltk.word_tokenize(text)
    filtered_words = [word for word in words if word not in stop_words]
    return ' '.join(filtered_words)

In [ ]:
reset_df['filtered_text'] = reset_df['clean_tweet'].apply(filter_stop_words)

# Print the updated DataFrame
reset_df

,Username,clean_tweet,filtered_text
0,diffusionbot,here are the images you requested courtesy of...,images requested courtesy stablediffusionpleas...
1,aneesmerchant,calls for stricter uk oversight of workplace a...,calls stricter uk oversight workplace ai amid ...
2,aneesmerchant,a ninefigure raise in fintech oh my artificia...,ninefigure raise fintech oh artificialintellig...
3,c4chaos,midjourney prompt ross playing guitar dressed...,midjourney prompt ross playing guitar dressed ...
4,_nxmstagram,my highlight of the daywith the right prompts ...,highlight daywith right prompts anything possi...
...,...,...,...
12495,SpirosMargaris,successful generativeai examples worth noting ...,successful generativeai examples worth noting ...
12496,SpirosMargaris,hot takes about the wild new world of generat...,hot takes wild new world generativeai fintech ...
12497,SpirosMargaris,we are the artist generativeai and the future ...,artist generativeai future art fintech ai arti...
12498,andresvilarino,top intelligentautomationtrends to lookout fo...,top intelligentautomationtrends lookout automa...
12499,SpirosMargaris,understanding generativeai its impacts and lim...,understanding generativeai impacts limitations...

In [ ]:
test_text_stopwords = reset_df['filtered_text'][0]
test_text_stopwords

'images requested courtesy stablediffusionplease retweet amp enjoyed images generativeai generativeart aiart promptsharing'

In [ ]:
sentiment_scores = analyzer.polarity_scores(test_text_stopwords)
print(sentiment_scores)

{'neg': 0.0, 'neu': 0.633, 'pos': 0.367, 'compound': 0.7003}

In [ ]:
def get_sentiment_score(test_text_stopwords: str):
  return analyzer.polarity_scores(test_text_stopwords)

In [ ]:
# Apply sentiment score and create new column of top 30 tweet counts
reset_df['sentiment_score'] = reset_df['filtered_text'].apply(get_sentiment_score)

reset_df

,Username,clean_tweet,filtered_text,sentiment_score
0,diffusionbot,here are the images you requested courtesy of...,images requested courtesy stablediffusionpleas...,"{'neg': 0.0, 'neu': 0.633, 'pos': 0.367, 'comp..."
1,aneesmerchant,calls for stricter uk oversight of workplace a...,calls stricter uk oversight workplace ai amid ...,"{'neg': 0.177, 'neu': 0.823, 'pos': 0.0, 'comp..."
2,aneesmerchant,a ninefigure raise in fintech oh my artificia...,ninefigure raise fintech oh artificialintellig...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
3,c4chaos,midjourney prompt ross playing guitar dressed...,midjourney prompt ross playing guitar dressed ...,"{'neg': 0.0, 'neu': 0.833, 'pos': 0.167, 'comp..."
4,_nxmstagram,my highlight of the daywith the right prompts ...,highlight daywith right prompts anything possi...,"{'neg': 0.0, 'neu': 0.888, 'pos': 0.112, 'comp..."
...,...,...,...,...
12495,SpirosMargaris,successful generativeai examples worth noting ...,successful generativeai examples worth noting ...,"{'neg': 0.0, 'neu': 0.551, 'pos': 0.449, 'comp..."
12496,SpirosMargaris,hot takes about the wild new world of generat...,hot takes wild new world generativeai fintech ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
12497,SpirosMargaris,we are the artist generativeai and the future ...,artist generativeai future art fintech ai arti...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
12498,andresvilarino,top intelligentautomationtrends to lookout fo...,top intelligentautomationtrends lookout automa...,"{'neg': 0.0, 'neu': 0.859, 'pos': 0.141, 'comp..."
12499,SpirosMargaris,understanding generativeai its impacts and lim...,understanding generativeai impacts limitations...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."

#Below is data processing to get total count of Tweets using datetime column

In [ ]:
string_datetime = df['Datetime'].tolist()

string_datetime[0:5]

['2023-04-19 21:27:19+00:00',
 '2023-04-19 21:27:09+00:00',
 '2023-04-19 21:26:57+00:00',
 '2023-04-19 21:26:49+00:00',
 '2023-04-19 21:25:00+00:00']

In [ ]:
# This is the way we want to format the date
format_date = '%a %b %d %H:%M:%S %z %Y'

converted_date = []

# Loop through each date and format
for date_string in string_datetime:
    converted_datetime = datetime.strptime(date_string, "%Y-%m-%d %H:%M:%S%z").replace(tzinfo=timezone.utc)
    converted_date.append(converted_datetime)
converted_date[0:5]

[datetime.datetime(2023, 4, 19, 21, 27, 19, tzinfo=datetime.timezone.utc),
 datetime.datetime(2023, 4, 19, 21, 27, 9, tzinfo=datetime.timezone.utc),
 datetime.datetime(2023, 4, 19, 21, 26, 57, tzinfo=datetime.timezone.utc),
 datetime.datetime(2023, 4, 19, 21, 26, 49, tzinfo=datetime.timezone.utc),
 datetime.datetime(2023, 4, 19, 21, 25, tzinfo=datetime.timezone.utc)]

In [ ]:
tweet_counts = {}
#Loop through converted dates and find DOW and HOR
for dates in converted_date:
    day = dates.strftime('%A')
    hour = dates.strftime('%H')

    # Create day of week and hour of day key value pair here
    key = (day, hour)

    # Update tweet counts dictionary
    if key in tweet_counts:
        tweet_counts[key] += 1
    else:
        tweet_counts[key] = 1

In [ ]:
# Create data to graph
graph_data = []
for key, count in tweet_counts.items():
    day, hour = key
    graph_data.append({'day': day, 'hour': hour, 'count': count})

print(graph_data[0:5])

[{'day': 'Wednesday', 'hour': '21', 'count': 422}, {'day': 'Wednesday', 'hour': '20', 'count': 459}, {'day': 'Wednesday', 'hour': '19', 'count': 467}, {'day': 'Wednesday', 'hour': '18', 'count': 543}, {'day': 'Wednesday', 'hour': '17', 'count': 558}]

In [ ]:
graph_df = pd.DataFrame(graph_data)
y_order = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
graph_df

           day hour  count
0    Wednesday   21    422
1    Wednesday   20    459
2    Wednesday   19    467
3    Wednesday   18    543
4    Wednesday   17    558
..         ...  ...    ...
163   Thursday   02    206
164   Thursday   01    199
165   Thursday   00    249
166  Wednesday   23    210
167  Wednesday   22    334

[168 rows x 3 columns]

# Visualizations

HeatMap of Tweets 7 days **bold text**

In [ ]:
# Sort by Sunday-Monday
day_order = ['Sunday', 'Monday', 'Tueday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']


heatmap = alt.Chart(graph_df).mark_rect().encode(
    x=alt.X('hour:O',title='Hour of Day'),
    y=alt.Y('day:O',sort = day_order,title='Day of Week'),
    color=alt.Color('count:Q',title = 'Tweet Count'),
    tooltip=['day', 'hour', 'count']
).properties(
    title = 'Tweet Counts by Day and Hour',
    width=800,
    height=600
)

heatmap

alt.Chart(...)